spring:
  profiles:
    group:
      common:
        - db
        - oauth
      dev:
        - common
        - openapi
      prod:
        - common
        - openapi
      test:
        - common

logging:
  level:
    sql: debug