spring:
  profiles:
    group:
      common:
        - db
        - oauth
        - image
        - url
      dev:
        - common
        - openapi
      prod:
        - common
        - openapi
      test:
        - common

logging:
  level:
    root: INFO
    sql: DEBUG
    org.springframework.web: TRACE
    com.ssu.goodplassu: TRACE
